/**
 * Creative Concept Library
 * --------------------------------------------------------------------
 * A Creative Concept is NOT a layout. It is a complete art direction
 * system — the visual IDEA behind a post.
 *
 * Each concept defines:
 *   - Story: what narrative does this tell?
 *   - Emotion: what should the viewer feel?
 *   - Visual Metaphor: what image communicates the idea?
 *   - Focal Points: what does the eye notice first, then second?
 *   - Photography Style: what imagery supports this?
 *   - Design System: typography, color, grid, spacing, texture,
 *       background, decorative elements, logo placement, hierarchy
 *   - Inspiration: what brand/aesthetic informed this direction?
 *
 * The AI Concept Director reads these specs and chooses which concept
 * best serves the user's content. The renderer then fills that concept
 * with the user's words — content never drives the visual direction.
 *
 * "I want this post to feel like an Apple keynote."
 * NOT
 * "I'll place the headline at x=80."
 */
import { NEON } from '@/lib/marketingTokens';

function concept(id, name, family, inspiration, story, emotion, metaphor, focalPoints, photography, design, accentColor) {
  return { id, name, family, inspiration, story, emotion, visualMetaphor: metaphor, focalPoints, photographyStyle: photography, designSystem: design, accentColor: accentColor || NEON.purple };
}

export const CONCEPT_LIBRARY = [
  // ═══ POSTER FAMILY ═══
  concept(
    'movie_poster', 'Movie Poster', 'poster',
    'A24 / Criterion film posters',
    'A single dramatic moment frozen in light and shadow — the anticipation before the story begins.',
    'Cinematic awe, weighty anticipation',
    'A spotlight cutting through absolute darkness — one truth illuminated',
    ['The headline, massive and bottom-weighted', 'The vast darkness above, holding tension'],
    'Single light source, deep shadows, high-contrast cinematic color grade, anamorphic warmth',
    { typography: 'Black Han Sans, condensed and heavy, bottom-anchored. DM Sans for credits, tiny and tracked wide.',
      colorTreatment: 'Near-black background (#050308), single warm accent, minimal palette',
      grid: 'Full-bleed atmospheric zone above, content compressed to bottom third',
      spacing: 'Dramatic vertical negative space — the emptiness IS the design',
      texture: 'Subtle vignette, film grain warmth',
      background: 'Deep cinematic black with warm light bloom from one direction',
      decorativeElements: 'Credits block, thin border frame, rating tag',
      logoPlacement: 'Bottom-left, small, alongside credits',
      hierarchy: 'Light/atmosphere → Headline → Subheadline → Credits' },
    NEON.purple,
  ),
  concept(
    'concert_flyer', 'Concert Flyer', 'poster',
    'DIY show flyers, punk xerography',
    'Raw energy compressed onto a single sheet — the urgency of a show happening TONIGHT.',
    'Electric urgency, underground energy',
    'Overlapping noise — too much information, all of it loud, all of it alive',
    ['Stacked rotated headline, screaming from center', 'Date/venue info pile at bottom'],
    'High-contrast flash photography, motion blur, sweat and lights',
    { typography: 'Black Han Sans, rotated and stacked, overlapping lines. DM Sans condensed for info.',
      colorTreatment: 'Pure black with neon green + pink accents, xerox-contrast',
      grid: 'Center-stacked, rotated elements, deliberate chaos',
      spacing: 'Tight, compressed, no breathing room — urgency',
      texture: 'Xerox toner feel, high contrast',
      background: 'Solid black with neon glow bursts',
      decorativeElements: 'Starbursts, arrows, underlines, emphasis marks',
      logoPlacement: 'Buried in the info pile, small',
      hierarchy: 'Headline (rotated) → Date/Venue → Details → Logo' },
    NEON.green,
  ),
  concept(
    'street_poster', 'Street Poster', 'poster',
    'Wheatpasted street posters, guerrilla art',
    'A message slapped on a wall — raw, immediate, impossible to ignore.',
    'Rebellious, grassroots, authentic',
    'Layered paper on brick — each layer a voice, torn edges revealing what came before',
    ['Bold stencil headline, top-weighted', 'Torn paper edges framing the message'],
    'Urban textures, brick, concrete, wheatpaste residue',
    { typography: 'Black Han Sans, stencil-cut feel, heavy. DM Sans for body, slightly distressed spacing.',
      colorTreatment: 'Off-white/cream paper on dark, black ink, one neon accent',
      grid: 'Asymmetric, torn-edge borders, content slightly off-center',
      spacing: 'Irregular, organic — not grid-aligned',
      texture: 'Paper texture, torn edges, subtle distress',
      background: 'Dark wall tone with cream paper card overlaid',
      decorativeElements: 'Torn edge borders, tape strips, spray accent',
      logoPlacement: 'Bottom corner, stamped feel',
      hierarchy: 'Headline → Body → CTA → Stamp' },
    NEON.pink,
  ),
  concept(
    'subway_ad', 'Subway Advertisement', 'poster',
    'NYC MTA subway car advertisements',
    'A captive audience, 30 seconds of attention, one message that must land before the next stop.',
    'Direct, utilitarian, urban-professional',
    'A sign in transit — bold, legible, impossible to miss from across the platform',
    ['Dominant headline in the visual zone', 'Info bar strip at bottom'],
    'Clean product photography on white, or bold flat-color zones',
    { typography: 'Black Han Sans for headline, massive. DM Sans bold for info, tracked.',
      colorTreatment: 'Horizontal color bands, high contrast, transit-signage palette',
      grid: 'Top color band → visual zone → bottom info bar',
      spacing: 'Structured horizontal bands, generous padding within zones',
      texture: 'Clean, flat, no texture — signage quality',
      background: 'Color-banded: accent top, dark middle, accent bottom',
      decorativeElements: 'Route bullet, directional arrows, border frame',
      logoPlacement: 'Bottom info bar, left-aligned',
      hierarchy: 'Color band → Headline → Visual → Info bar' },
    NEON.cyan,
  ),
  concept(
    'neon_sign', 'Neon Sign', 'poster',
    'Las Vegas signage, Tokyo Shibuya neon',
    'A sign glowing in the night — a beacon promising something exciting inside.',
    'Nocturnal excitement, electric allure',
    'Glass tubes bending light into words — the glow IS the message',
    ['Glowing neon headline, center', 'Secondary glow elements around it'],
    'Night photography, glowing signs, wet streets reflecting light',
    { typography: 'Black Han Sans with heavy text-shadow glow, appearing as illuminated tubes. DM Sans for secondary glow text.',
      colorTreatment: 'Dark wall background, multiple neon colors (green, pink, cyan, yellow)',
      grid: 'Center-anchored, sign-like framing',
      spacing: 'Generous dark space around glowing elements — the dark makes the glow',
      texture: 'Dark wall/brick texture, subtle reflection',
      background: 'Very dark (#020203) with wall texture',
      decorativeElements: 'Sign frame border, mounting bolts, secondary glow accents',
      logoPlacement: 'Bottom, small glow text',
      hierarchy: 'Neon headline → Glow subheadline → Frame → Logo' },
    NEON.pink,
  ),

  // ═══ DOCUMENT FAMILY ═══
  concept(
    'receipt', 'Receipt', 'document',
    'Thermal receipt paper, point-of-sale prints',
    'Proof of transaction — the mundane artifact that proves something real happened.',
    'Grounded, authentic, tangible',
    'A narrow paper strip — everything reduced to its most essential, most honest form',
    ['Itemized content stack, centered and narrow', 'Total/summary at bottom'],
    'None — this is pure typography on paper',
    { typography: 'Monospace throughout (DM Sans mono fallback). No display font. All caps, tracked.',
      colorTreatment: 'White/cream paper on dark background, black ink, no color',
      grid: 'Single narrow column, centered, max-width ~50%',
      spacing: 'Tight line height, itemized, dotted dividers',
      texture: 'Thermal paper — slight cream tint, subtle paper grain',
      background: 'Dark backdrop with cream paper card centered',
      decorativeElements: 'Dotted dividers, asterisk separators, timestamp, transaction ID',
      logoPlacement: 'Top of receipt, centered, small',
      hierarchy: 'Merchant → Items → Divider → Total → Footer' },
    NEON.green,
  ),
  concept(
    'parking_ticket', 'Parking Ticket', 'document',
    'Dashboard parking permits, municipal forms',
    'Official authorization — a physical pass that grants access to a specific place and time.',
    'Official, authorized, place-specific',
    'A permit on a dashboard — proof you belong here, right now',
    ['Bold permit header at top of card', 'Info fields (section/row/seat) in grid below'],
    'None — formal document aesthetic',
    { typography: 'DM Sans bold for labels and values. Black Han Sans only for the permit title.',
      colorTreatment: 'Card on dark bg, white card with accent border, official stamp color',
      grid: 'Bordered card, perforated feel, field grid below header',
      spacing: 'Structured form fields, label-above-value pattern',
      texture: 'Card stock, perforated edge feel',
      background: 'Dark bg, white/light card centered',
      decorativeElements: 'Perforation line, official stamp/seal, barcode strip, serial number',
      logoPlacement: 'Card header, centered',
      hierarchy: 'Permit title → Fields grid → Stamp → Barcode' },
    NEON.cyan,
  ),
  concept(
    'backstage_pass', 'Backstage Pass', 'document',
    'Lanyard credentials, festival all-access passes',
    'Exclusive access — the credential that separates the audience from the inner circle.',
    'Exclusive, privileged, insider',
    'A badge on a lanyard — your key to the world behind the curtain',
    ['ALL ACCESS credential text, center of card', 'Lanyard strip visible at top'],
    'Photo ID area, holographic foil accents',
    { typography: 'Black Han Sans for ACCESS text, massive. DM Sans for credential details.',
      colorTreatment: 'Dark card with holographic accent strip, neon green for access level',
      grid: 'Lanyard strip top → photo zone → credential text → bottom strip',
      spacing: 'Card-structured, centered, credential zones',
      texture: 'Holographic foil strip, card gloss',
      background: 'Dark card on darker bg, holographic accent',
      decorativeElements: 'Lanyard attachment, holographic strip, barcode, photo placeholder, credential number',
      logoPlacement: 'Bottom of card, small',
      hierarchy: 'Lanyard → ACCESS text → Photo → Details → Barcode' },
    NEON.green,
  ),
  concept(
    'vip_wristband', 'VIP Wristband', 'document',
    'Fabric/Tyvek festival wristbands',
    "You're in — the physical marker that says you belong to this experience.",
    'Belonging, festival energy, physical memory',
    'A band around your wrist — the simplest possible proof of participation',
    ['VIP text centered on the band', 'Pattern repeating along the band length'],
    'None — pure material design',
    { typography: 'Black Han Sans for VIP, repeated. DM Sans mono for serial number.',
      colorTreatment: 'Wristband color (neon accent) on dark, pattern in band color',
      grid: 'Horizontal band across canvas center',
      spacing: 'Repeating pattern, even distribution along band',
      texture: 'Fabric/Tyvek weave texture, subtle',
      background: 'Dark with band strip across center',
      decorativeElements: 'Repeating pattern, security serial, closure clip, event branding',
      logoPlacement: 'On the band, small, repeated',
      hierarchy: 'VIP text → Pattern → Serial → Logo' },
    NEON.pink,
  ),
  concept(
    'ticket_stub', 'Ticket Stub', 'document',
    'Vintage Admit One tickets, stubbed concert tickets',
    'A memory you can hold — the torn ticket that proves you were there.',
    'Nostalgic, tangible, sentimental',
    'A torn ticket stub — the perforation separating what you kept from what they took',
    ['ADMIT ONE header on the stub', 'Main event info on the body'],
    'None — vintage print aesthetic',
    { typography: 'Black Han Sans for ADMIT ONE and event title. DM Sans for seat info, condensed.',
      colorTreatment: 'Ticket color (cream/aged paper) on dark, ink print, vintage accent',
      grid: 'Left stub (~25%) + perforation + right main body (~75%)',
      spacing: 'Stub is compact info, body is full event details',
      texture: 'Aged paper, slight yellowing, print texture',
      background: 'Dark bg, cream ticket card with perforation',
      decorativeElements: 'Perforation line, serial number, seat fields, vintage ornament, barcode',
      logoPlacement: 'Stub corner, small',
      hierarchy: 'ADMIT ONE → Event title → Date/Venue → Seat → Serial' },
    NEON.yellow,
  ),

  // ═══ EDITORIAL FAMILY ═══
  concept(
    'magazine_cover', 'Magazine Cover', 'editorial',
    'The New Yorker, Time, Rolling Stone',
    'A story worth the cover — the single most important thing this issue has to say.',
    'Authoritative, curated, newsworthy',
    'A magazine on a rack — one cover fighting for attention among dozens',
    ['Masthead title at top, massive', 'Cover headline centered, with cover lines flanking'],
    'Editorial portrait photography, cover-grade',
    { typography: 'Black Han Sans for masthead, massive. DM Sans for cover lines and headlines.',
      colorTreatment: 'Full-bleed image or gradient, white text, one accent color for cover lines',
      grid: 'Masthead top → cover zone (headline + image) → cover lines left/right → footer bar',
      spacing: 'Structured magazine grid, cover lines do not overlap headline',
      texture: 'Glossy magazine finish, clean',
      background: 'Image or rich gradient, editorial quality',
      decorativeElements: 'Masthead, issue date, barcode, cover line bullets, price tag',
      logoPlacement: 'In the masthead zone, top',
      hierarchy: 'Masthead → Cover headline → Cover lines → Issue info' },
    NEON.purple,
  ),
  concept(
    'minimal_editorial', 'Minimal Editorial', 'editorial',
    'Kinfolk, Cereal, Apartamento magazines',
    'Quiet confidence — so important it needs nothing but space.',
    'Calm, refined, contemplative',
    'A single object on a vast empty table — the absence makes the presence powerful',
    ['Tiny centered content, lower third', 'The vast empty space above'],
    'Minimal, lots of negative space, soft natural light',
    { typography: 'DM Sans light for everything. Minimal weight, generous tracking. No display font.',
      colorTreatment: 'Monochrome — dark bg, white text, one hairline accent',
      grid: 'Everything centered, lower third only',
      spacing: 'EXTREME whitespace — 60%+ of canvas is empty',
      texture: 'None — pure flat color',
      background: 'Flat dark, no gradients, no glows',
      decorativeElements: 'One thin hairline accent, nothing else',
      logoPlacement: 'Bottom center, tiny',
      hierarchy: 'Whitespace → Headline (small) → Subheadline → Hairline → Logo' },
    NEON.cyan,
  ),
  concept(
    'newspaper', 'Newspaper', 'editorial',
    'The New York Times front page, broadsheet journalism',
    'The record of what happened — set in type, committed to print, above the fold.',
    'Authoritative, trustworthy, archival',
    'Ink on newsprint — the weight of recorded fact',
    ['Bold headline above the fold, centered', 'Multi-column body below'],
    'Photojournalism, black and white, documentary',
    { typography: 'Black Han Sans for headline (denser, smaller than usual). DM Sans serif-feel for body, multi-column.',
      colorTreatment: 'Newsprint — cream/off-white paper, black ink, no color',
      grid: 'Multi-column (2-3 columns), rules between, masthead top',
      spacing: 'Dense, column-based, tight leading',
      texture: 'Newsprint paper, slight grain',
      background: 'Dark bg, cream newsprint card',
      decorativeElements: 'Column rules, masthead, dateline, page number, folio',
      logoPlacement: 'In masthead, top center',
      hierarchy: 'Masthead → Headline → Dateline → Columns → Folio' },
    NEON.cyan,
  ),
  concept(
    'breaking_news', 'Breaking News', 'editorial',
    'CNN, BBC, Fox News lower-thirds and breaking banners',
    'This just in — urgent, developing, happening right now.',
    'Urgent, alarming, immediate',
    'A red banner cutting across the screen — your attention is not optional',
    ['BREAKING red banner at top', 'Headline in the lower-third graphic zone'],
    'Live broadcast screenshots, newsroom',
    { typography: 'Black Han Sans for BREAKING and headline. DM Sans bold for ticker text.',
      colorTreatment: 'Red banner (#FF2D78), dark lower-third, white text, ticker accent',
      grid: 'Red banner top → visual zone → lower-third headline → ticker bar bottom',
      spacing: 'Banner edges, lower-third padding, ticker tight',
      texture: 'Broadcast graphics — clean, no texture',
      background: 'Dark with red banner and lower-third overlay',
      decorativeElements: 'Red BREAKING banner, live indicator, ticker bar, time stamp, network bug',
      logoPlacement: 'Network bug, top corner',
      hierarchy: 'BREAKING banner → Headline → Subheadline → Ticker → Time' },
    NEON.pink,
  ),
  concept(
    'premium_invitation', 'Premium Invitation', 'editorial',
    'Wedding invitations, gala programs, luxury event stationery',
    'You are cordially invited — an occasion so significant it deserves its own artifact.',
    'Elegant, formal, honored',
    'A gilded envelope opened carefully — the ceremony begins with the paper',
    ['Centered formal headline', 'Thin gold border frame around everything'],
    'None — pure typography and ornament',
    { typography: 'DM Sans light, generous letter-spacing, formal. Black Han Sans for the event title, restrained.',
      colorTreatment: 'Dark bg, gold/cream text, thin gold border frame',
      grid: 'Perfectly centered, symmetric, formal',
      spacing: 'Generous, balanced, symmetrical margins',
      texture: 'Subtle paper grain, gold foil accent',
      background: 'Deep dark with gold border frame inset',
      decorativeElements: 'Gold border frame, ornamental dividers, monogram, RSVP line',
      logoPlacement: 'Bottom center, small, formal',
      hierarchy: 'Border → Ornament → Title → Details → Date → Monogram' },
    NEON.yellow,
  ),
  concept(
    'handwritten_notes', 'Handwritten Notes', 'editorial',
    'Moleskine notebooks, journal entries, margin doodles',
    'A thought scratched out in private — raw, personal, unpolished on purpose.',
    'Intimate, honest, personal',
    'A notebook open on a desk — pen marks, crossed-out words, arrows connecting ideas',
    ['Handwritten-style headline in the ruling', 'Margin doodles and arrows around it'],
    'None — notebook aesthetic',
    { typography: 'DM Sans italic, casual, slightly irregular sizing. No display font.',
      colorTreatment: 'Lined paper — white/cream bg, blue rules, red margin, ink text',
      grid: 'Horizontal ruled lines, left margin line, content flows along rules',
      spacing: 'Lines match the ruling, natural handwriting spacing',
      texture: 'Paper with blue horizontal rules and red margin line',
      background: 'Lined paper on dark bg',
      decorativeElements: 'Blue ruling lines, red margin, arrows, stars, underlines, doodles',
      logoPlacement: 'Bottom corner, handwritten style',
      hierarchy: 'Ruling → Headline → Body → Doodles → Signature' },
    NEON.green,
  ),

  // ═══ TECH FAMILY ═══
  concept(
    'apple_keynote', 'Apple Keynote', 'tech',
    'Apple presentation slides, product reveal keynotes',
    'One idea, perfectly expressed, with nothing competing for attention.',
    'Clarity, confidence, premium minimalism',
    'A single sentence in a dark room — the confidence to say nothing else',
    ['One bold statement, dead center, massive', 'Nothing else — the void is the design'],
    'None — pure typography',
    { typography: 'DM Sans, ultra-bold, massive, centered. No display font. Perfect kerning.',
      colorTreatment: 'Pure black (#000000), white text, no accent color',
      grid: 'Dead center, nothing else',
      spacing: 'Infinite — the entire canvas is the statement',
      texture: 'None — pure flat black',
      background: '#000000, absolutely nothing else',
      decorativeElements: 'NONE. Zero decorative elements.',
      logoPlacement: 'None on the slide, or tiny bottom-center',
      hierarchy: 'Statement → (nothing) → (nothing) → (nothing)' },
    NEON.green,
  ),
  concept(
    'tech_launch', 'Tech Launch', 'tech',
    'Stripe, Linear, Vercel product launch pages',
    'A new thing exists — here it is, here is why it matters, here is how it works.',
    'Sophisticated, modern, product-forward',
    'A product on a pedestal — lit perfectly, presented with reverence',
    ['Product headline with gradient accent', 'Feature highlights in a clean stack'],
    'Product screenshots, UI mockups, clean studio renders',
    { typography: 'DM Sans, bold but not display. Gradient text for headline. Mono accents for technical labels.',
      colorTreatment: 'Dark gradient bg, neon gradient accents (green to cyan), clean whites',
      grid: 'Centered headline → subheadline → feature stack → CTA',
      spacing: 'Generous, modern SaaS spacing',
      texture: 'Subtle gradient mesh background',
      background: 'Dark gradient with gradient mesh accents',
      decorativeElements: 'Gradient accent line, feature bullets, code-like labels, version badge',
      logoPlacement: 'Top-left or centered top, modern',
      hierarchy: 'Badge → Headline (gradient) → Subheadline → Features → CTA' },
    NEON.cyan,
  ),
  concept(
    'spotify_wrapped', 'Spotify Wrapped', 'tech',
    'Spotify Wrapped, year-in-review data stories',
    'Your year, your stats, your story — data made personal and vibrant.',
    'Playful, celebratory, data-excited',
    'A burst of color and numbers — your life quantified and celebrated',
    ['Massive stat number, center, vibrant', 'Supporting label and context below'],
    'None — pure color and type',
    { typography: 'DM Sans, ultra-bold, massive numbers. Tight tracking, playful casing.',
      colorTreatment: 'VIBRANT — solid bold color bg (not dark!), contrasting text, multi-color accents',
      grid: 'Center-stacked stat display, big numbers',
      spacing: 'Tight, energetic, no whitespace waste',
      texture: 'Flat bold color, no texture',
      background: 'Solid vibrant color (green, purple, or pink) — NOT dark',
      decorativeElements: 'Stat bars, percentage rings, color blocks, emoji-like accents',
      logoPlacement: 'Top corner, white, simple',
      hierarchy: 'Stat number → Label → Context → CTA → Logo' },
    NEON.green,
  ),
  concept(
    'blueprint', 'Blueprint', 'tech',
    'Architectural blueprints, engineering schematics',
    'A plan drawn before building — precise, measured, technical.',
    'Precise, technical, authoritative',
    'A drafting table — grid lines, measurements, annotations in the margins',
    ['Technical headline with measurement marks', 'Grid structure visible behind content'],
    'None — technical drawing aesthetic',
    { typography: 'DM Sans monospace feel, tracked, technical. All caps, annotation-style.',
      colorTreatment: 'Navy blue bg (#0a1929), cyan grid lines, white/cyan text',
      grid: 'Visible grid (20px squares), content aligned to grid, annotations in margins',
      spacing: 'Grid-aligned, measurement-marked, technical',
      texture: 'Grid pattern background, blueprint paper',
      background: 'Navy blue with visible cyan grid',
      decorativeElements: 'Grid lines, measurement marks, dimension lines, corner annotations, title block',
      logoPlacement: 'Title block, bottom-right corner',
      hierarchy: 'Title block → Grid → Headline → Annotations → Dimensions' },
    NEON.cyan,
  ),
  concept(
    'jumbotron', 'Jumbotron', 'tech',
    'Arena LED scoreboards, stadium screens',
    'The big screen in the arena — loud, bright, visible from the last row.',
    'Spectacle, scale, arena energy',
    'A massive LED screen — pixels of light forming the biggest text you have ever seen',
    ['Massive scoreboard headline, center', 'Score/stat elements flanking'],
    'None — LED pixel aesthetic',
    { typography: 'Black Han Sans, massive, glowing. Scoreboard-style numbering.',
      colorTreatment: 'LED dark frame, bright text colors (green, cyan, yellow on black)',
      grid: 'Scoreboard layout — header bar, main display, stat row',
      spacing: 'Framed, bordered zones like a scoreboard',
      texture: 'LED dot/pixel pattern background',
      background: 'Very dark with LED pixel dot pattern',
      decorativeElements: 'LED dot pattern, scoreboard frame, stat boxes, clock display, team colors',
      logoPlacement: 'Scoreboard corner, small',
      hierarchy: 'Frame → Headline (LED glow) → Stats → Clock → Logo' },
    NEON.green,
  ),
  concept(
    'seat_map', 'Seat Map', 'tech',
    'Venue seating charts, Ticketmaster interactive maps',
    'Your place in the crowd — the overhead view showing exactly where you will be.',
    'Oriented, prepared, anticipating',
    'A map with one seat highlighted — your seat, in the bigger picture',
    ['Highlighted seat/section in the venue grid', 'Stage indicator at top'],
    'None — overhead diagram aesthetic',
    { typography: 'DM Sans, small, label-style. Bold for section labels, regular for seat numbers.',
      colorTreatment: 'Dark bg, seat dots in muted color, highlighted section in accent',
      grid: 'Grid of seat dots, stage at top, highlighted section in center',
      spacing: 'Even dot grid, section groupings',
      texture: 'None — flat diagram',
      background: 'Dark, flat, diagram-style',
      decorativeElements: 'Seat dot grid, stage shape, section labels, highlighted zone, compass/north indicator',
      logoPlacement: 'Bottom corner, small',
      hierarchy: 'Stage → Seat grid → Highlighted section → Section label → Info' },
    NEON.cyan,
  ),

  // ═══ ATMOSPHERIC FAMILY ═══
  concept(
    'broken_glass', 'Broken Glass', 'atmospheric',
    'Shattered glass photography, fracture art',
    'Something broke — and the break IS the story. The cracks reveal the truth.',
    'Disruption, fracture, uncomfortable truth',
    'A shattered pane — each fragment showing a different angle of the same reality',
    ['Fractured headline with crack overlay', 'Glass fragment shards scattered around'],
    'Macro photography of broken glass, fractures, shards',
    { typography: 'Black Han Sans with crack overlay lines crossing through. Fractured feel.',
      colorTreatment: 'Dark bg, white/gradient text, crack lines in white, shard borders',
      grid: 'Centered with crack lines and shard elements breaking the grid',
      spacing: 'Tension — shards push against text, cracks cross through',
      texture: 'Glass fracture lines, shard fragments, sharp edges',
      background: 'Very dark with fracture line overlays',
      decorativeElements: 'Crack lines, glass shard fragments, sharp angular borders, dust particles',
      logoPlacement: 'Bottom, behind a shard',
      hierarchy: 'Cracks → Fractured headline → Shards → Subheadline → Logo' },
    NEON.purple,
  ),
  concept(
    'empty_seat', 'Empty Seat', 'atmospheric',
    'Lonely chair photography, absence art',
    'The seat is empty — and the emptiness says everything.',
    'Melancholy, longing, emotional weight',
    'A single empty chair in a vast arena — the absence is louder than any crowd',
    ['The empty seat/illuminated spot, small in frame', 'The vast dark space surrounding it'],
    'Low-light photography, single illuminated point in darkness',
    { typography: 'DM Sans, light weight, small, emotionally restrained. Not bold.',
      colorTreatment: 'Near-black bg, single warm light spot, muted text',
      grid: 'Content in lower third, vast empty space above',
      spacing: 'ENORMOUS negative space — 70%+ empty',
      texture: 'Darkness with a single soft light source',
      background: 'Near-black with one soft warm glow',
      decorativeElements: 'Single light glow, subtle floor line, nothing else',
      logoPlacement: 'Bottom corner, very small, muted',
      hierarchy: 'Empty space → Light glow → Headline (small) → Subheadline → Logo' },
    NEON.purple,
  ),
  concept(
    'spotlight', 'Spotlight', 'atmospheric',
    'Theatrical stage lighting, dramatic spotlights',
    'All eyes here — the moment the lights find you and everything else disappears.',
    'Dramatic, theatrical, center-stage',
    'A cone of light in a dark theater — the performer in the beam, everything else shadow',
    ['Content in the spotlight cone, center', 'Darkness surrounding the light'],
    'Stage photography, spotlight beams, haze and smoke',
    { typography: 'Black Han Sans, illuminated and bright in the light. Text fades at edges.',
      colorTreatment: 'Dark stage bg, bright spotlight cone, content lit by the light',
      grid: 'Spotlight cone from top, content centered in the beam',
      spacing: 'Content centered in light, generous dark space around beam',
      texture: 'Haze/smoke in the light beam, stage floor',
      background: 'Dark stage with spotlight cone',
      decorativeElements: 'Spotlight cone beam, haze particles, stage floor edge, light fixture glow at top',
      logoPlacement: 'Bottom, in the light pool',
      hierarchy: 'Spotlight cone → Headline (lit) → Subheadline → Stage → Logo' },
    NEON.yellow,
  ),
  concept(
    'arena_lighting', 'Arena Lighting', 'atmospheric',
    'Concert light shows, stadium light beams',
    'The lights hit and the crowd erupts — pure spectacle, pure energy.',
    'Electric, ecstatic, overwhelming energy',
    'Beams of colored light cutting through haze — the visual equivalent of a drop',
    ['Headline in the center of the light beams', 'Colored beam elements radiating outward'],
    'Concert photography, light beams, laser shows, haze',
    { typography: 'Black Han Sans, bright, energetic. Glowing text in beam colors.',
      colorTreatment: 'Dark bg, multiple colored light beams (purple, pink, green, cyan)',
      grid: 'Light beams radiating from top, content in the beam intersection',
      spacing: 'Dynamic, beam-driven layout',
      texture: 'Haze/smoke in the beams, light particles',
      background: 'Dark with multiple colored beam gradients',
      decorativeElements: 'Light beam cones, haze particles, color washes, beam intersection glow',
      logoPlacement: 'Bottom corner, in a color wash',
      hierarchy: 'Light beams → Headline (in beams) → Subheadline → Color wash → Logo' },
    NEON.purple,
  ),
  concept(
    'bw_documentary', 'Black & White Documentary', 'atmospheric',
    'Photojournalism, Magnum Photos, documentary photography',
    'The unvarnished truth — no color to distract, just light, shadow, and fact.',
    'Raw, honest, weight of reality',
    'A black and white photograph — the absence of color makes you see more',
    ['Bold headline overlaid on the image zone', 'Caption-style text at bottom'],
    'Black and white documentary photography, high contrast, grain',
    { typography: 'Black Han Sans for headline, stark white. DM Sans for caption, small, photo-caption style.',
      colorTreatment: 'PURE grayscale — no color at all. Black, white, grays only.',
      grid: 'Image zone (top 65%) + caption zone (bottom 35%)',
      spacing: 'Image dominates, caption is tight and informational',
      texture: 'Film grain, high-contrast B&W',
      background: 'Black and white gradient or image, grayscale only',
      decorativeElements: 'Caption bar, photo credit, date stamp, grain overlay',
      logoPlacement: 'Caption bar, small',
      hierarchy: 'B&W image → Headline overlay → Caption → Credit → Logo' },
    NEON.cyan,
  ),

  // ═══ BRAND FAMILY ═══
  concept(
    'luxury_fashion', 'Luxury Fashion Ad', 'brand',
    'Vogue, Dior, Hermes print advertisements',
    'Desire distilled — one image, one word, one feeling of wanting.',
    'Aspirational, refined, covetous',
    'A full-page fashion ad — the image does 90% of the work, the text whispers',
    ['The image/visual zone, massive', 'Minimal text anchored at bottom'],
    'High-fashion editorial photography, studio lit, impeccable',
    { typography: 'DM Sans, ultra-light weight for body. Black Han Sans restrained for the brand name only.',
      colorTreatment: 'Full-bleed image or rich gradient, white text, minimal accent',
      grid: 'Full-bleed visual (75%) + text bar bottom (25%)',
      spacing: 'Image-dominant, text is whisper-quiet at bottom',
      texture: 'Glossy magazine finish',
      background: 'Image or rich dark gradient, editorial quality',
      decorativeElements: 'Thin brand wordmark, minimal — nothing decorative',
      logoPlacement: 'Bottom-center, wordmark style, refined',
      hierarchy: 'Image → Brand wordmark → Tagline → (nothing else)' },
    NEON.purple,
  ),
  concept(
    'sports_broadcast', 'Sports Broadcast', 'brand',
    'ESPN, Fox Sports, NBC broadcast graphics',
    'Game day energy — stats, scores, and the electricity of competition.',
    'Competitive, energized, stat-driven',
    'A broadcast lower-third — the info you need, styled like you are watching the game',
    ['Bold stat/headline in the graphic zone', 'Scoreboard elements flanking'],
    'Sports photography, action shots, dynamic angles',
    { typography: 'Black Han Sans, bold and angled. DM Sans bold for stats and figures.',
      colorTreatment: 'Bold team-color background, white text, accent stripes',
      grid: 'Angled graphic zones, stat boxes, dynamic diagonal elements',
      spacing: 'Energetic, slightly compressed, broadcast-paced',
      texture: 'Clean broadcast graphics, subtle diagonal stripes',
      background: 'Bold color (team-color feel) with diagonal accents',
      decorativeElements: 'Stat boxes, score ticker, team color stripes, record indicator, broadcast frame',
      logoPlacement: 'Broadcast bug, corner',
      hierarchy: 'Headline → Stat box → Score ticker → Frame → Logo' },
    NEON.orange,
  ),
  concept(
    'financial_report', 'Financial Report', 'brand',
    'Bloomberg terminal, annual reports, WSJ graphics',
    'The numbers, clearly stated — performance you can measure.',
    'Professional, trustworthy, data-confident',
    'A clean data dashboard — every number earns its space',
    ['Key stat/figure, prominent', 'Supporting data points in a clean grid'],
    'None — data visualization aesthetic',
    { typography: 'DM Sans, clean and professional. Mono for figures. No display font.',
      colorTreatment: 'Dark professional bg, white text, green for positive, muted grays',
      grid: 'Structured data grid, card-based, aligned columns',
      spacing: 'Clean, grid-aligned, professional spacing',
      texture: 'None — clean digital surface',
      background: 'Dark professional (#0a0a0f), subtle grid',
      decorativeElements: 'Data cards, trend indicators, grid lines, figure labels, source citations',
      logoPlacement: 'Header, professional',
      hierarchy: 'Header → Key stat → Data grid → Source → Logo' },
    NEON.green,
  ),
  concept(
    'formula_one', 'Formula 1', 'brand',
    'F1 poster graphics, racing liveries, motorsport design',
    'Speed, precision, and the pursuit of milliseconds.',
    'Adrenaline, precision, elite performance',
    'A car at speed — motion blur, carbon fiber, the blur of the track',
    ['Dynamic angled headline, implying motion', 'Speed line elements racing across'],
    'Motorsport photography, carbon fiber textures, speed',
    { typography: 'Black Han Sans, italic/angled, implying forward motion. DM Sans bold for technical labels.',
      colorTreatment: 'Carbon fiber dark bg, racing red/silver accents, speed lines',
      grid: 'Diagonal/angled elements, motion-implying layout',
      spacing: 'Dynamic, compressed in direction of motion',
      texture: 'Carbon fiber weave pattern, speed lines',
      background: 'Carbon fiber texture dark with speed lines',
      decorativeElements: 'Speed lines, carbon fiber texture, racing number, technical labels, chevron accents',
      logoPlacement: 'Corner, alongside racing number',
      hierarchy: 'Speed lines → Angled headline → Technical label → Racing number → Logo' },
    NEON.orange,
  ),
];

export function getConceptById(id) {
  return CONCEPT_LIBRARY.find(c => c.id === id);
}

export function getConceptsByFamily(family) {
  return CONCEPT_LIBRARY.filter(c => c.family === family);
}

export const CONCEPT_FAMILIES = ['poster', 'document', 'editorial', 'tech', 'atmospheric', 'brand'];

export const CONCEPT_FAMILY_LABELS = {
  poster: 'Poster',
  document: 'Document',
  editorial: 'Editorial',
  tech: 'Tech',
  atmospheric: 'Atmospheric',
  brand: 'Brand',
};