/**
 * Creative Concepts — Structured Design System Definitions
 * --------------------------------------------------------------------
 * Decision 2 of 3: What visual metaphor best communicates the message?
 *
 * A Creative Concept is NOT a component. It is NOT a layout.
 * It is structured design data that describes a complete art direction.
 *
 * The Creative Direction Engine reads this data and constructs the
 * graphic dynamically. No per-concept rendering code exists.
 *
 * Each concept defines:
 *   - inspiration + references (Inspiration Board)
 *   - mood, visual language, visual metaphor
 *   - a structured designSystem the engine interprets:
 *       background, composition, typography, color, texture,
 *       decorative elements, logo placement, hierarchy
 *
 * The AI extracts design PRINCIPLES from references — it must never
 * recreate or copy them. It blends their characteristics into
 * Peanut Gallery's existing design language.
 */
import { NEON, NEON_RGB, GRADIENTS, THEMES } from '@/lib/marketingTokens';

// ── Defaults (concepts override only what differs) ──────────────────────
const DEFAULT_TYPOGRAPHY = {
  headline:    { font: 'display', weight: 'heavy',  transform: 'none',     tracking: 'normal',     scale: 1.0 },
  subheadline: { font: 'body',    weight: 'normal',  transform: 'none',     tracking: 'normal',     scale: 1.0 },
  body:        { font: 'body',    weight: 'normal',  transform: 'none',     tracking: 'normal',     scale: 1.0 },
  cta:         { font: 'body',    weight: 'bold',    transform: 'uppercase', tracking: 'wide',      scale: 1.0 },
  badge:       { font: 'body',    weight: 'bold',    transform: 'uppercase', tracking: 'extra-wide', scale: 1.0 },
  stat:        { font: 'display', weight: 'heavy',  transform: 'none',     tracking: 'normal',     scale: 1.0 },
};

const DEFAULT_BG = { type: 'radial-glow', baseColor: '#050308', glow: { color: NEON.purple, x: 15, y: -5, intensity: 0.10 } };
const DEFAULT_COMPOSITION = { anchor: 'center', alignment: 'center', negativeSpace: 0.3, maxWidth: 0.85, rotation: 0 };
const DEFAULT_COLOR = { text: 'white', accent: NEON.purple, palette: [NEON.purple, NEON.pink, NEON.green], textGradient: GRADIENTS.headline };
const DEFAULT_TEXTURE = { type: 'none', intensity: 0 };
const DEFAULT_LOGO = { position: 'bottom-center', size: 'sm' };

function concept(data) {
  return {
    id: data.id,
    name: data.name,
    family: data.family,
    inspiration: data.inspiration,
    references: data.references || [],
    mood: data.mood,
    visualLanguage: data.visualLanguage,
    visualMetaphor: data.visualMetaphor,
    focalPoints: data.focalPoints,
    photographyStyle: data.photographyStyle || 'none',
    designSystem: {
      background:   { ...DEFAULT_BG, ...data.designSystem?.background },
      composition:  { ...DEFAULT_COMPOSITION, ...data.designSystem?.composition },
      typography:   { ...DEFAULT_TYPOGRAPHY, ...data.designSystem?.typography },
      color:        { ...DEFAULT_COLOR, ...data.designSystem?.color },
      texture:      { ...DEFAULT_TEXTURE, ...data.designSystem?.texture },
      decorative:   data.designSystem?.decorative || [],
      logo:         { ...DEFAULT_LOGO, ...data.designSystem?.logo },
      hierarchy:    data.designSystem?.hierarchy || ['badge', 'headline', 'subheadline', 'body', 'cta'],
    },
  };
}

export const CREATIVE_CONCEPTS = [
  // ═══ POSTER FAMILY ═══
  concept({
    id: 'movie_poster', name: 'Movie Poster', family: 'poster',
    inspiration: 'A24 / Criterion film posters',
    references: ['A24', 'Criterion Collection', 'Saul Bass', 'Wong Kar-wai'],
    mood: 'Cinematic awe, weighty anticipation',
    visualLanguage: 'High-contrast, dramatic single light source, deep shadows',
    visualMetaphor: 'A spotlight cutting through absolute darkness — one truth illuminated',
    focalPoints: ['The headline, massive and bottom-weighted', 'The vast darkness above, holding tension'],
    photographyStyle: 'Single light source, deep shadows, anamorphic warmth',
    designSystem: {
      background: { type: 'radial-glow', baseColor: '#020203', glow: { color: NEON.purple, x: 30, y: 70, intensity: 0.25 } },
      composition: { anchor: 'bottom', alignment: 'center', negativeSpace: 0.55, maxWidth: 0.85 },
      typography: {
        headline: { font: 'display', weight: 'heavy', transform: 'none', tracking: 'normal', scale: 1.3 },
        subheadline: { font: 'body', weight: 'normal', tracking: 'wide', scale: 0.9 },
        body: { font: 'body', weight: 'normal', scale: 0.85 },
      },
      color: { text: 'white', accent: NEON.purple, palette: [NEON.purple, '#ffffff'], textGradient: null },
      texture: { type: 'vignette', intensity: 0.5 },
      decorative: ['thin_border', 'credits_block'],
      logo: { position: 'bottom-left', size: 'xs' },
      hierarchy: ['headline', 'subheadline', 'body', 'credits_block'],
    },
  }),
  concept({
    id: 'concert_flyer', name: 'Concert Flyer', family: 'poster',
    inspiration: 'DIY show flyers, punk xerography',
    references: ['Punk flyers', 'Xerox art', 'Coachella posters', 'Frank Kozik'],
    mood: 'Electric urgency, underground energy',
    visualLanguage: 'High-contrast xerox, overlapping noise, neon on black',
    visualMetaphor: 'Overlapping noise — too much information, all of it loud, all of it alive',
    focalPoints: ['Stacked rotated headline, screaming from center', 'Date/venue info pile at bottom'],
    designSystem: {
      background: { type: 'flat', baseColor: '#000000', glow: { color: NEON.green, x: 50, y: 50, intensity: 0.12 } },
      composition: { anchor: 'center', alignment: 'center', negativeSpace: 0.1, maxWidth: 0.9, rotation: -3 },
      typography: {
        headline: { font: 'display', weight: 'heavy', transform: 'uppercase', tracking: 'normal', scale: 1.4 },
        subheadline: { font: 'body', weight: 'bold', transform: 'uppercase', tracking: 'wide', scale: 1.0 },
        body: { font: 'body', weight: 'bold', transform: 'uppercase', scale: 0.85 },
      },
      color: { text: 'white', accent: NEON.green, palette: [NEON.green, NEON.pink, '#ffffff'], textGradient: GRADIENTS.broken },
      texture: { type: 'grain', intensity: 0.3 },
      decorative: ['starburst', 'arrows', 'info_pile'],
      logo: { position: 'bottom-right', size: 'xs' },
      hierarchy: ['headline', 'subheadline', 'body', 'info_pile'],
    },
  }),
  concept({
    id: 'street_poster', name: 'Street Poster', family: 'poster',
    inspiration: 'Wheatpasted street posters, guerrilla art',
    references: ['Shepard Fairey', 'Banksy', 'Wheatpaste art', 'Street art'],
    mood: 'Rebellious, grassroots, authentic',
    visualLanguage: 'Layered paper on brick, torn edges, stencil type',
    visualMetaphor: 'Layered paper on brick — each layer a voice, torn edges revealing what came before',
    focalPoints: ['Bold stencil headline, top-weighted', 'Torn paper edges framing the message'],
    designSystem: {
      background: { type: 'flat', baseColor: '#0d0b08', glow: null },
      composition: { anchor: 'top', alignment: 'left', negativeSpace: 0.2, maxWidth: 0.8 },
      typography: {
        headline: { font: 'display', weight: 'heavy', transform: 'uppercase', tracking: 'normal', scale: 1.2 },
        body: { font: 'body', weight: 'normal', scale: 0.9 },
      },
      color: { text: 'white', accent: NEON.pink, palette: [NEON.pink, '#ffffff', '#d4cfc4'], textGradient: null },
      texture: { type: 'grain', intensity: 0.2 },
      decorative: ['torn_border', 'tape_strip', 'spray_accent'],
      logo: { position: 'bottom-left', size: 'xs' },
      hierarchy: ['headline', 'body', 'cta'],
    },
  }),
  concept({
    id: 'subway_ad', name: 'Subway Advertisement', family: 'poster',
    inspiration: 'NYC MTA subway car advertisements',
    references: ['MTA NYC', 'Subway ads', 'Massimo Vignelli', 'Transit signage'],
    mood: 'Direct, utilitarian, urban-professional',
    visualLanguage: 'Bold flat-color bands, high contrast, signage legibility',
    visualMetaphor: 'A sign in transit — bold, legible, impossible to miss from across the platform',
    focalPoints: ['Dominant headline in the visual zone', 'Info bar strip at bottom'],
    designSystem: {
      background: { type: 'banded', baseColor: '#0a0a0f', glow: null, bands: [{ color: NEON.cyan, position: 'top' }, { color: '#0a0a0f', position: 'middle' }, { color: NEON.cyan, position: 'bottom' }] },
      composition: { anchor: 'center', alignment: 'center', negativeSpace: 0.25, maxWidth: 0.9 },
      typography: {
        headline: { font: 'display', weight: 'heavy', transform: 'uppercase', tracking: 'normal', scale: 1.5 },
        subheadline: { font: 'body', weight: 'bold', tracking: 'wide', scale: 1.0 },
      },
      color: { text: 'white', accent: NEON.cyan, palette: [NEON.cyan, '#ffffff'], textGradient: null },
      texture: { type: 'none', intensity: 0 },
      decorative: ['route_bullet', 'border_frame'],
      logo: { position: 'bottom-left', size: 'sm' },
      hierarchy: ['badge', 'headline', 'subheadline', 'body', 'cta'],
    },
  }),
  concept({
    id: 'neon_sign', name: 'Neon Sign', family: 'poster',
    inspiration: 'Las Vegas signage, Tokyo Shibuya neon',
    references: ['Las Vegas signs', 'Shibuya neon', 'Tokyo nightlife', 'Blade Runner'],
    mood: 'Nocturnal excitement, electric allure',
    visualLanguage: 'Glowing tubes in darkness, multiple neon colors, wall texture',
    visualMetaphor: 'Glass tubes bending light into words — the glow IS the message',
    focalPoints: ['Glowing neon headline, center', 'Secondary glow elements around it'],
    designSystem: {
      background: { type: 'flat', baseColor: '#020203', glow: { color: NEON.pink, x: 50, y: 50, intensity: 0.15 } },
      composition: { anchor: 'center', alignment: 'center', negativeSpace: 0.4, maxWidth: 0.8 },
      typography: {
        headline: { font: 'display', weight: 'heavy', transform: 'uppercase', tracking: 'wide', scale: 1.3 },
        subheadline: { font: 'body', weight: 'bold', transform: 'uppercase', tracking: 'wide', scale: 0.9 },
      },
      color: { text: 'white', accent: NEON.pink, palette: [NEON.green, NEON.pink, NEON.cyan, NEON.yellow], textGradient: null },
      texture: { type: 'none', intensity: 0 },
      decorative: ['sign_frame', 'glow_accents'],
      logo: { position: 'bottom-center', size: 'xs' },
      hierarchy: ['headline', 'subheadline', 'cta'],
    },
  }),

  // ═══ DOCUMENT FAMILY ═══
  concept({
    id: 'receipt', name: 'Receipt', family: 'document',
    inspiration: 'Thermal receipt paper, point-of-sale prints',
    references: ['Thermal receipts', 'POS prints', 'CVS receipts', 'Restaurant checks'],
    mood: 'Grounded, authentic, tangible',
    visualLanguage: 'Monospace, narrow column, dotted dividers, no color',
    visualMetaphor: 'A narrow paper strip — everything reduced to its most essential, most honest form',
    focalPoints: ['Itemized content stack, centered and narrow', 'Total/summary at bottom'],
    designSystem: {
      background: { type: 'flat', baseColor: '#0a0a0a', glow: null },
      composition: { anchor: 'center', alignment: 'center', negativeSpace: 0.3, maxWidth: 0.5 },
      typography: {
        headline: { font: 'body', weight: 'bold', transform: 'uppercase', tracking: 'wide', scale: 1.0 },
        subheadline: { font: 'body', weight: 'normal', transform: 'uppercase', tracking: 'wide', scale: 0.8 },
        body: { font: 'body', weight: 'normal', transform: 'none', tracking: 'normal', scale: 0.8 },
        cta: { font: 'body', weight: 'bold', transform: 'uppercase', tracking: 'wide', scale: 0.85 },
      },
      color: { text: 'white', accent: NEON.green, palette: ['#ffffff', '#d4cfc4'], textGradient: null },
      texture: { type: 'paper', intensity: 0.15 },
      decorative: ['dotted_dividers', 'timestamp', 'transaction_id', 'paper_card'],
      logo: { position: 'top-center', size: 'xs' },
      hierarchy: ['badge', 'headline', 'body', 'dotted_dividers', 'cta'],
    },
  }),
  concept({
    id: 'parking_ticket', name: 'Parking Ticket', family: 'document',
    inspiration: 'Dashboard parking permits, municipal forms',
    references: ['Parking permits', 'DMV forms', 'Municipal passes', 'Dashboard tickets'],
    mood: 'Official, authorized, place-specific',
    visualLanguage: 'Bordered card, perforated edge, form-field grid, stamp',
    visualMetaphor: 'A permit on a dashboard — proof you belong here, right now',
    focalPoints: ['Bold permit header at top of card', 'Info fields (section/row/seat) in grid below'],
    designSystem: {
      background: { type: 'flat', baseColor: '#080808', glow: null },
      composition: { anchor: 'center', alignment: 'center', negativeSpace: 0.25, maxWidth: 0.75 },
      typography: {
        headline: { font: 'display', weight: 'heavy', transform: 'uppercase', tracking: 'wide', scale: 1.1 },
        subheadline: { font: 'body', weight: 'bold', tracking: 'wide', scale: 0.9 },
      },
      color: { text: 'white', accent: NEON.cyan, palette: [NEON.cyan, '#ffffff'], textGradient: null },
      texture: { type: 'paper', intensity: 0.1 },
      decorative: ['perforation', 'official_stamp', 'barcode', 'field_grid', 'card_frame'],
      logo: { position: 'top-center', size: 'xs' },
      hierarchy: ['badge', 'headline', 'subheadline', 'field_grid', 'body', 'barcode'],
    },
  }),
  concept({
    id: 'backstage_pass', name: 'Backstage Pass', family: 'document',
    inspiration: 'Lanyard credentials, festival all-access passes',
    references: ['Festival passes', 'Lanyard credentials', 'Coachella VIP', 'Security badges'],
    mood: 'Exclusive, privileged, insider',
    visualLanguage: 'Lanyard strip, holographic accent, credential zones, card gloss',
    visualMetaphor: 'A badge on a lanyard — your key to the world behind the curtain',
    focalPoints: ['ALL ACCESS credential text, center of card', 'Lanyard strip visible at top'],
    designSystem: {
      background: { type: 'flat', baseColor: '#060608', glow: { color: NEON.green, x: 50, y: 50, intensity: 0.08 } },
      composition: { anchor: 'center', alignment: 'center', negativeSpace: 0.2, maxWidth: 0.7 },
      typography: {
        headline: { font: 'display', weight: 'heavy', transform: 'uppercase', tracking: 'wide', scale: 1.4 },
        subheadline: { font: 'body', weight: 'bold', tracking: 'wide', scale: 0.85 },
      },
      color: { text: 'white', accent: NEON.green, palette: [NEON.green, '#ffffff', NEON.cyan], textGradient: null },
      texture: { type: 'none', intensity: 0 },
      decorative: ['lanyard_strip', 'holographic_strip', 'barcode', 'card_frame'],
      logo: { position: 'bottom-center', size: 'xs' },
      hierarchy: ['lanyard_strip', 'badge', 'headline', 'subheadline', 'body', 'barcode'],
    },
  }),
  concept({
    id: 'vip_wristband', name: 'VIP Wristband', family: 'document',
    inspiration: 'Fabric/Tyvek festival wristbands',
    references: ['Festival wristbands', 'Tyvek bands', 'Coachella wristbands', 'Event credentials'],
    mood: 'Belonging, festival energy, physical memory',
    visualLanguage: 'Horizontal band, repeating pattern, fabric texture, serial number',
    visualMetaphor: 'A band around your wrist — the simplest possible proof of participation',
    focalPoints: ['VIP text centered on the band', 'Pattern repeating along the band length'],
    designSystem: {
      background: { type: 'flat', baseColor: '#050505', glow: null },
      composition: { anchor: 'center', alignment: 'center', negativeSpace: 0.35, maxWidth: 0.9 },
      typography: {
        headline: { font: 'display', weight: 'heavy', transform: 'uppercase', tracking: 'wide', scale: 1.3 },
        body: { font: 'body', weight: 'normal', transform: 'uppercase', tracking: 'wide', scale: 0.8 },
      },
      color: { text: 'white', accent: NEON.pink, palette: [NEON.pink, '#ffffff'], textGradient: null },
      texture: { type: 'paper', intensity: 0.2 },
      decorative: ['wristband_band', 'repeating_pattern', 'serial_number'],
      logo: { position: 'bottom-center', size: 'xs' },
      hierarchy: ['headline', 'subheadline', 'body', 'serial_number'],
    },
  }),
  concept({
    id: 'ticket_stub', name: 'Ticket Stub', family: 'document',
    inspiration: 'Vintage Admit One tickets, stubbed concert tickets',
    references: ['Admit One tickets', 'Vintage concert stubs', 'Rolling tickets', 'StubHub'],
    mood: 'Nostalgic, tangible, sentimental',
    visualLanguage: 'Aged paper, perforation divide, vintage ink, ornament',
    visualMetaphor: 'A torn ticket stub — the perforation separating what you kept from what they took',
    focalPoints: ['ADMIT ONE header on the stub', 'Main event info on the body'],
    designSystem: {
      background: { type: 'flat', baseColor: '#0a0805', glow: null },
      composition: { anchor: 'center', alignment: 'center', negativeSpace: 0.2, maxWidth: 0.85 },
      typography: {
        headline: { font: 'display', weight: 'heavy', transform: 'uppercase', tracking: 'wide', scale: 1.2 },
        subheadline: { font: 'body', weight: 'bold', tracking: 'wide', scale: 0.9 },
      },
      color: { text: 'white', accent: NEON.yellow, palette: [NEON.yellow, '#d4cfc4', '#ffffff'], textGradient: null },
      texture: { type: 'paper', intensity: 0.25 },
      decorative: ['perforation', 'serial_number', 'vintage_ornament', 'barcode', 'ticket_card'],
      logo: { position: 'bottom-left', size: 'xs' },
      hierarchy: ['badge', 'headline', 'subheadline', 'body', 'serial_number'],
    },
  }),

  // ═══ EDITORIAL FAMILY ═══
  concept({
    id: 'magazine_cover', name: 'Magazine Cover', family: 'editorial',
    inspiration: 'The New Yorker, Time, Rolling Stone',
    references: ['The New Yorker', 'Time Magazine', 'Rolling Stone', 'Vogue'],
    mood: 'Authoritative, curated, newsworthy',
    visualLanguage: 'Masthead top, cover headline center, cover lines flanking, full-bleed visual',
    visualMetaphor: 'A magazine on a rack — one cover fighting for attention among dozens',
    focalPoints: ['Masthead title at top, massive', 'Cover headline centered, with cover lines flanking'],
    photographyStyle: 'Editorial portrait photography, cover-grade',
    designSystem: {
      background: { type: 'radial-glow', baseColor: '#08060c', glow: { color: NEON.purple, x: 50, y: 30, intensity: 0.15 } },
      composition: { anchor: 'center', alignment: 'center', negativeSpace: 0.2, maxWidth: 0.85 },
      typography: {
        headline: { font: 'display', weight: 'heavy', transform: 'uppercase', tracking: 'normal', scale: 1.3 },
        subheadline: { font: 'body', weight: 'bold', tracking: 'wide', scale: 0.95 },
        body: { font: 'body', weight: 'normal', scale: 0.85 },
      },
      color: { text: 'white', accent: NEON.purple, palette: [NEON.purple, '#ffffff'], textGradient: null },
      texture: { type: 'none', intensity: 0 },
      decorative: ['masthead', 'cover_lines', 'issue_date', 'barcode'],
      logo: { position: 'top-center', size: 'sm' },
      hierarchy: ['masthead', 'headline', 'subheadline', 'cover_lines', 'body'],
    },
  }),
  concept({
    id: 'minimal_editorial', name: 'Minimal Editorial', family: 'editorial',
    inspiration: 'Kinfolk, Cereal, Apartamento magazines',
    references: ['Kinfolk', 'Cereal Magazine', 'Apartamento', 'MUJI'],
    mood: 'Calm, refined, contemplative',
    visualLanguage: 'Extreme whitespace, light weights, single hairline accent, no decoration',
    visualMetaphor: 'A single object on a vast empty table — the absence makes the presence powerful',
    focalPoints: ['Tiny centered content, lower third', 'The vast empty space above'],
    designSystem: {
      background: { type: 'flat', baseColor: '#050505', glow: null },
      composition: { anchor: 'lower-third', alignment: 'center', negativeSpace: 0.65, maxWidth: 0.6 },
      typography: {
        headline: { font: 'body', weight: 'light', transform: 'none', tracking: 'wide', scale: 1.0 },
        subheadline: { font: 'body', weight: 'light', tracking: 'wide', scale: 0.85 },
        body: { font: 'body', weight: 'light', scale: 0.8 },
      },
      color: { text: 'white', accent: '#666666', palette: ['#ffffff', '#888888'], textGradient: null },
      texture: { type: 'none', intensity: 0 },
      decorative: ['hairline_accent'],
      logo: { position: 'bottom-center', size: 'xs' },
      hierarchy: ['headline', 'subheadline', 'hairline_accent', 'body'],
    },
  }),
  concept({
    id: 'newspaper', name: 'Newspaper', family: 'editorial',
    inspiration: 'The New York Times front page, broadsheet journalism',
    references: ['The New York Times', 'Broadsheet journalism', 'The Guardian', 'Reuters'],
    mood: 'Authoritative, trustworthy, archival',
    visualLanguage: 'Multi-column, cream paper, dense type, column rules, masthead',
    visualMetaphor: 'Ink on newsprint — the weight of recorded fact',
    focalPoints: ['Bold headline above the fold, centered', 'Multi-column body below'],
    designSystem: {
      background: { type: 'flat', baseColor: '#080806', glow: null },
      composition: { anchor: 'top', alignment: 'center', negativeSpace: 0.15, maxWidth: 0.85 },
      typography: {
        headline: { font: 'display', weight: 'heavy', transform: 'none', tracking: 'normal', scale: 1.1 },
        subheadline: { font: 'body', weight: 'bold', tracking: 'normal', scale: 0.9 },
        body: { font: 'body', weight: 'normal', scale: 0.8 },
      },
      color: { text: 'white', accent: '#d4cfc4', palette: ['#ffffff', '#d4cfc4'], textGradient: null },
      texture: { type: 'paper', intensity: 0.2 },
      decorative: ['masthead', 'column_rules', 'dateline', 'folio', 'newsprint_card'],
      logo: { position: 'top-center', size: 'xs' },
      hierarchy: ['masthead', 'headline', 'dateline', 'subheadline', 'body', 'folio'],
    },
  }),
  concept({
    id: 'breaking_news', name: 'Breaking News', family: 'editorial',
    inspiration: 'CNN, BBC, Fox News lower-thirds and breaking banners',
    references: ['CNN', 'BBC News', 'Fox News', 'Reuters breaking'],
    mood: 'Urgent, alarming, immediate',
    visualLanguage: 'Red banner top, lower-third graphic, ticker bar, live indicator',
    visualMetaphor: 'A red banner cutting across the screen — your attention is not optional',
    focalPoints: ['BREAKING red banner at top', 'Headline in the lower-third graphic zone'],
    designSystem: {
      background: { type: 'flat', baseColor: '#0a0608', glow: { color: NEON.pink, x: 50, y: 0, intensity: 0.1 } },
      composition: { anchor: 'bottom', alignment: 'left', negativeSpace: 0.3, maxWidth: 0.85 },
      typography: {
        headline: { font: 'display', weight: 'heavy', transform: 'uppercase', tracking: 'normal', scale: 1.2 },
        subheadline: { font: 'body', weight: 'bold', tracking: 'wide', scale: 0.9 },
      },
      color: { text: 'white', accent: NEON.pink, palette: [NEON.pink, '#ffffff', NEON.cyan], textGradient: null },
      texture: { type: 'none', intensity: 0 },
      decorative: ['breaking_banner', 'live_indicator', 'ticker_bar', 'timestamp'],
      logo: { position: 'top-right', size: 'xs' },
      hierarchy: ['breaking_banner', 'headline', 'subheadline', 'body', 'ticker_bar'],
    },
  }),
  concept({
    id: 'premium_invitation', name: 'Premium Invitation', family: 'editorial',
    inspiration: 'Wedding invitations, gala programs, luxury event stationery',
    references: ['Wedding invitations', 'Gala programs', 'Luxury stationery', 'Mr. Cup'],
    mood: 'Elegant, formal, honored',
    visualLanguage: 'Gold border frame, centered formal type, ornamental dividers, symmetrical',
    visualMetaphor: 'A gilded envelope opened carefully — the ceremony begins with the paper',
    focalPoints: ['Centered formal headline', 'Thin gold border frame around everything'],
    designSystem: {
      background: { type: 'flat', baseColor: '#06060a', glow: null },
      composition: { anchor: 'center', alignment: 'center', negativeSpace: 0.35, maxWidth: 0.65 },
      typography: {
        headline: { font: 'display', weight: 'normal', transform: 'uppercase', tracking: 'extra-wide', scale: 1.0 },
        subheadline: { font: 'body', weight: 'light', tracking: 'wide', scale: 0.9 },
        body: { font: 'body', weight: 'light', tracking: 'normal', scale: 0.85 },
      },
      color: { text: 'white', accent: NEON.yellow, palette: [NEON.yellow, '#ffffff', '#d4cfc4'], textGradient: null },
      texture: { type: 'paper', intensity: 0.1 },
      decorative: ['gold_border', 'ornamental_divider', 'monogram'],
      logo: { position: 'bottom-center', size: 'xs' },
      hierarchy: ['gold_border', 'headline', 'ornamental_divider', 'subheadline', 'body', 'monogram'],
    },
  }),
  concept({
    id: 'handwritten_notes', name: 'Handwritten Notes', family: 'editorial',
    inspiration: 'Moleskine notebooks, journal entries, margin doodles',
    references: ['Moleskine', 'Journal entries', 'Field Notes', 'Margin doodles'],
    mood: 'Intimate, honest, personal',
    visualLanguage: 'Lined paper, blue rules, red margin, italic casual type, doodles',
    visualMetaphor: 'A notebook open on a desk — pen marks, crossed-out words, arrows connecting ideas',
    focalPoints: ['Handwritten-style headline in the ruling', 'Margin doodles and arrows around it'],
    designSystem: {
      background: { type: 'flat', baseColor: '#060606', glow: null },
      composition: { anchor: 'center', alignment: 'left', negativeSpace: 0.25, maxWidth: 0.8 },
      typography: {
        headline: { font: 'body', weight: 'normal', transform: 'none', tracking: 'normal', scale: 1.1 },
        subheadline: { font: 'body', weight: 'normal', scale: 0.95 },
        body: { font: 'body', weight: 'normal', scale: 0.85 },
      },
      color: { text: 'white', accent: NEON.green, palette: ['#ffffff', NEON.green, '#8888cc'], textGradient: null },
      texture: { type: 'paper', intensity: 0.3 },
      decorative: ['ruled_lines', 'red_margin', 'doodles', 'arrows'],
      logo: { position: 'bottom-left', size: 'xs' },
      hierarchy: ['ruled_lines', 'headline', 'body', 'doodles', 'signature'],
    },
  }),

  // ═══ TECH FAMILY ═══
  concept({
    id: 'apple_keynote', name: 'Apple Keynote', family: 'tech',
    inspiration: 'Apple presentation slides, product reveal keynotes',
    references: ['Apple Keynote', 'Steve Jobs presentations', 'Apple product reveals'],
    mood: 'Clarity, confidence, premium minimalism',
    visualLanguage: 'Pure flat black, one centered statement, nothing else',
    visualMetaphor: 'A single sentence in a dark room — the confidence to say nothing else',
    focalPoints: ['One bold statement, dead center, massive', 'Nothing else — the void is the design'],
    designSystem: {
      background: { type: 'flat', baseColor: '#000000', glow: null },
      composition: { anchor: 'center', alignment: 'center', negativeSpace: 0.6, maxWidth: 0.7 },
      typography: {
        headline: { font: 'body', weight: 'heavy', transform: 'none', tracking: 'normal', scale: 1.3 },
        subheadline: { font: 'body', weight: 'normal', tracking: 'normal', scale: 0.9 },
      },
      color: { text: 'white', accent: '#ffffff', palette: ['#ffffff'], textGradient: null },
      texture: { type: 'none', intensity: 0 },
      decorative: [],
      logo: { position: 'none', size: 'xs' },
      hierarchy: ['headline', 'subheadline'],
    },
  }),
  concept({
    id: 'tech_launch', name: 'Tech Launch', family: 'tech',
    inspiration: 'Stripe, Linear, Vercel product launch pages',
    references: ['Stripe', 'Linear', 'Vercel', 'Figma'],
    mood: 'Sophisticated, modern, product-forward',
    visualLanguage: 'Gradient mesh bg, gradient headline, feature stack, clean SaaS',
    visualMetaphor: 'A product on a pedestal — lit perfectly, presented with reverence',
    focalPoints: ['Product headline with gradient accent', 'Feature highlights in a clean stack'],
    designSystem: {
      background: { type: 'radial-glow', baseColor: '#050308', glow: { color: NEON.cyan, x: 50, y: 20, intensity: 0.15 } },
      composition: { anchor: 'center', alignment: 'center', negativeSpace: 0.3, maxWidth: 0.8 },
      typography: {
        headline: { font: 'body', weight: 'heavy', transform: 'none', tracking: 'normal', scale: 1.2 },
        subheadline: { font: 'body', weight: 'normal', tracking: 'normal', scale: 0.95 },
        body: { font: 'body', weight: 'normal', scale: 0.85 },
      },
      color: { text: 'white', accent: NEON.cyan, palette: [NEON.green, NEON.cyan, '#ffffff'], textGradient: GRADIENTS.cta_primary },
      texture: { type: 'none', intensity: 0 },
      decorative: ['gradient_accent_line', 'feature_bullets', 'version_badge'],
      logo: { position: 'top-center', size: 'sm' },
      hierarchy: ['version_badge', 'headline', 'subheadline', 'body', 'cta'],
    },
  }),
  concept({
    id: 'spotify_wrapped', name: 'Spotify Wrapped', family: 'tech',
    inspiration: 'Spotify Wrapped, year-in-review data stories',
    references: ['Spotify Wrapped', 'Year in review', 'Strava recap', 'Apple Music recap'],
    mood: 'Playful, celebratory, data-excited',
    visualLanguage: 'Vibrant solid color bg, massive numbers, tight energetic layout',
    visualMetaphor: 'A burst of color and numbers — your life quantified and celebrated',
    focalPoints: ['Massive stat number, center, vibrant', 'Supporting label and context below'],
    designSystem: {
      background: { type: 'flat', baseColor: NEON.purple, glow: null },
      composition: { anchor: 'center', alignment: 'center', negativeSpace: 0.15, maxWidth: 0.85 },
      typography: {
        headline: { font: 'display', weight: 'heavy', transform: 'uppercase', tracking: 'normal', scale: 1.5 },
        stat: { font: 'display', weight: 'heavy', transform: 'none', tracking: 'normal', scale: 2.0 },
        subheadline: { font: 'body', weight: 'bold', transform: 'uppercase', tracking: 'wide', scale: 0.95 },
      },
      color: { text: 'dark', accent: NEON.yellow, palette: [NEON.green, NEON.pink, NEON.yellow], textGradient: null },
      texture: { type: 'none', intensity: 0 },
      decorative: ['stat_bars', 'color_blocks'],
      logo: { position: 'top-left', size: 'xs' },
      hierarchy: ['badge', 'stat', 'headline', 'subheadline', 'body', 'cta'],
    },
  }),
  concept({
    id: 'blueprint', name: 'Blueprint', family: 'tech',
    inspiration: 'Architectural blueprints, engineering schematics',
    references: ['Architectural blueprints', 'Engineering schematics', 'CAD drawings', 'Drafting'],
    mood: 'Precise, technical, authoritative',
    visualLanguage: 'Navy bg, visible cyan grid, annotation-style type, measurement marks',
    visualMetaphor: 'A drafting table — grid lines, measurements, annotations in the margins',
    focalPoints: ['Technical headline with measurement marks', 'Grid structure visible behind content'],
    designSystem: {
      background: { type: 'pattern-grid', baseColor: '#0a1929', glow: null, patternColor: 'rgba(0,200,255,0.08)' },
      composition: { anchor: 'center', alignment: 'left', negativeSpace: 0.3, maxWidth: 0.8 },
      typography: {
        headline: { font: 'body', weight: 'bold', transform: 'uppercase', tracking: 'wide', scale: 1.1 },
        subheadline: { font: 'body', weight: 'normal', transform: 'uppercase', tracking: 'wide', scale: 0.85 },
        body: { font: 'body', weight: 'normal', transform: 'uppercase', tracking: 'normal', scale: 0.8 },
      },
      color: { text: 'white', accent: NEON.cyan, palette: [NEON.cyan, '#ffffff'], textGradient: null },
      texture: { type: 'none', intensity: 0 },
      decorative: ['measurement_marks', 'dimension_lines', 'corner_annotations', 'title_block'],
      logo: { position: 'bottom-right', size: 'xs' },
      hierarchy: ['title_block', 'headline', 'subheadline', 'body', 'corner_annotations'],
    },
  }),
  concept({
    id: 'jumbotron', name: 'Jumbotron', family: 'tech',
    inspiration: 'Arena LED scoreboards, stadium screens',
    references: ['Arena LED scoreboards', 'Stadium screens', 'Sports jumbotrons', 'LED displays'],
    mood: 'Spectacle, scale, arena energy',
    visualLanguage: 'LED dot pattern, glowing text, scoreboard frame, stat boxes',
    visualMetaphor: 'A massive LED screen — pixels of light forming the biggest text you have ever seen',
    focalPoints: ['Massive scoreboard headline, center', 'Score/stat elements flanking'],
    designSystem: {
      background: { type: 'pattern-dots', baseColor: '#020203', glow: { color: NEON.green, x: 50, y: 50, intensity: 0.08 }, patternColor: 'rgba(0,255,135,0.06)' },
      composition: { anchor: 'center', alignment: 'center', negativeSpace: 0.2, maxWidth: 0.85 },
      typography: {
        headline: { font: 'display', weight: 'heavy', transform: 'uppercase', tracking: 'normal', scale: 1.4 },
        stat: { font: 'display', weight: 'heavy', transform: 'none', tracking: 'normal', scale: 1.8 },
      },
      color: { text: 'white', accent: NEON.green, palette: [NEON.green, NEON.cyan, NEON.yellow, '#ffffff'], textGradient: null },
      texture: { type: 'none', intensity: 0 },
      decorative: ['scoreboard_frame', 'stat_boxes', 'clock_display'],
      logo: { position: 'bottom-right', size: 'xs' },
      hierarchy: ['scoreboard_frame', 'headline', 'stat', 'subheadline', 'clock_display'],
    },
  }),
  concept({
    id: 'seat_map', name: 'Seat Map', family: 'tech',
    inspiration: 'Venue seating charts, Ticketmaster interactive maps',
    references: ['Venue seating charts', 'Ticketmaster maps', 'SeatGeek maps', 'Stadium diagrams'],
    mood: 'Oriented, prepared, anticipating',
    visualLanguage: 'Seat dot grid, stage indicator, highlighted section, overhead diagram',
    visualMetaphor: 'A map with one seat highlighted — your seat, in the bigger picture',
    focalPoints: ['Highlighted seat/section in the venue grid', 'Stage indicator at top'],
    designSystem: {
      background: { type: 'flat', baseColor: '#060608', glow: null },
      composition: { anchor: 'center', alignment: 'center', negativeSpace: 0.3, maxWidth: 0.85 },
      typography: {
        headline: { font: 'body', weight: 'bold', transform: 'uppercase', tracking: 'wide', scale: 1.0 },
        subheadline: { font: 'body', weight: 'normal', tracking: 'normal', scale: 0.85 },
      },
      color: { text: 'white', accent: NEON.cyan, palette: [NEON.cyan, '#ffffff', '#555555'], textGradient: null },
      texture: { type: 'none', intensity: 0 },
      decorative: ['seat_dot_grid', 'stage_shape', 'highlighted_zone', 'compass'],
      logo: { position: 'bottom-right', size: 'xs' },
      hierarchy: ['stage_shape', 'seat_dot_grid', 'highlighted_zone', 'headline', 'subheadline', 'body'],
    },
  }),

  // ═══ ATMOSPHERIC FAMILY ═══
  concept({
    id: 'broken_glass', name: 'Broken Glass', family: 'atmospheric',
    inspiration: 'Shattered glass photography, fracture art',
    references: ['Shattered glass photography', 'Fracture art', 'Cracked screen art'],
    mood: 'Disruption, fracture, uncomfortable truth',
    visualLanguage: 'Crack overlay lines, shard fragments, sharp angular borders, tension',
    visualMetaphor: 'A shattered pane — each fragment showing a different angle of the same reality',
    focalPoints: ['Fractured headline with crack overlay', 'Glass fragment shards scattered around'],
    designSystem: {
      background: { type: 'flat', baseColor: '#030203', glow: { color: NEON.purple, x: 50, y: 50, intensity: 0.08 } },
      composition: { anchor: 'center', alignment: 'center', negativeSpace: 0.3, maxWidth: 0.8 },
      typography: {
        headline: { font: 'display', weight: 'heavy', transform: 'uppercase', tracking: 'normal', scale: 1.3 },
        subheadline: { font: 'body', weight: 'bold', tracking: 'wide', scale: 0.9 },
      },
      color: { text: 'white', accent: NEON.purple, palette: [NEON.purple, NEON.pink, '#ffffff'], textGradient: GRADIENTS.broken },
      texture: { type: 'grain', intensity: 0.15 },
      decorative: ['crack_lines', 'shard_fragments', 'dust_particles'],
      logo: { position: 'bottom-center', size: 'xs' },
      hierarchy: ['crack_lines', 'headline', 'shard_fragments', 'subheadline', 'body'],
    },
  }),
  concept({
    id: 'empty_seat', name: 'Empty Seat', family: 'atmospheric',
    inspiration: 'Lonely chair photography, absence art',
    references: ['Lonely chair photography', 'Absence art', 'Edward Hopper', 'Minimal melancholy'],
    mood: 'Melancholy, longing, emotional weight',
    visualLanguage: 'Near-black bg, single warm light spot, enormous negative space, light type',
    visualMetaphor: 'A single empty chair in a vast arena — the absence is louder than any crowd',
    focalPoints: ['The empty seat/illuminated spot, small in frame', 'The vast dark space surrounding it'],
    designSystem: {
      background: { type: 'radial-glow', baseColor: '#020203', glow: { color: '#332211', x: 50, y: 60, intensity: 0.12 } },
      composition: { anchor: 'lower-third', alignment: 'center', negativeSpace: 0.7, maxWidth: 0.6 },
      typography: {
        headline: { font: 'body', weight: 'light', transform: 'none', tracking: 'wide', scale: 0.95 },
        subheadline: { font: 'body', weight: 'light', tracking: 'wide', scale: 0.8 },
      },
      color: { text: 'white', accent: '#553322', palette: ['#ffffff', '#886644'], textGradient: null },
      texture: { type: 'vignette', intensity: 0.4 },
      decorative: ['single_light_glow'],
      logo: { position: 'bottom-right', size: 'xs' },
      hierarchy: ['single_light_glow', 'headline', 'subheadline', 'body'],
    },
  }),
  concept({
    id: 'spotlight', name: 'Spotlight', family: 'atmospheric',
    inspiration: 'Theatrical stage lighting, dramatic spotlights',
    references: ['Theatrical lighting', 'Stage spotlights', 'Broadway', 'Concert beams'],
    mood: 'Dramatic, theatrical, center-stage',
    visualLanguage: 'Spotlight cone from top, haze in beam, content lit by light, dark stage',
    visualMetaphor: 'A cone of light in a dark theater — the performer in the beam, everything else shadow',
    focalPoints: ['Content in the spotlight cone, center', 'Darkness surrounding the light'],
    designSystem: {
      background: { type: 'radial-glow', baseColor: '#020203', glow: { color: NEON.yellow, x: 50, y: 0, intensity: 0.18 } },
      composition: { anchor: 'center', alignment: 'center', negativeSpace: 0.35, maxWidth: 0.7 },
      typography: {
        headline: { font: 'display', weight: 'heavy', transform: 'none', tracking: 'normal', scale: 1.3 },
        subheadline: { font: 'body', weight: 'bold', tracking: 'wide', scale: 0.9 },
      },
      color: { text: 'white', accent: NEON.yellow, palette: [NEON.yellow, '#ffffff'], textGradient: null },
      texture: { type: 'grain', intensity: 0.1 },
      decorative: ['spotlight_cone', 'haze_particles', 'stage_floor'],
      logo: { position: 'bottom-center', size: 'xs' },
      hierarchy: ['spotlight_cone', 'headline', 'subheadline', 'body', 'cta'],
    },
  }),
  concept({
    id: 'arena_lighting', name: 'Arena Lighting', family: 'atmospheric',
    inspiration: 'Concert light shows, stadium light beams',
    references: ['Concert light shows', 'Stadium beams', 'EDM production', 'Laser shows'],
    mood: 'Electric, ecstatic, overwhelming energy',
    visualLanguage: 'Multiple colored beam gradients radiating, haze, dynamic beam-driven layout',
    visualMetaphor: 'Beams of colored light cutting through haze — the visual equivalent of a drop',
    focalPoints: ['Headline in the center of the light beams', 'Colored beam elements radiating outward'],
    designSystem: {
      background: { type: 'radial-glow', baseColor: '#030208', glow: { color: NEON.purple, x: 50, y: 0, intensity: 0.2 } },
      composition: { anchor: 'center', alignment: 'center', negativeSpace: 0.25, maxWidth: 0.8 },
      typography: {
        headline: { font: 'display', weight: 'heavy', transform: 'uppercase', tracking: 'normal', scale: 1.3 },
        subheadline: { font: 'body', weight: 'bold', tracking: 'wide', scale: 0.9 },
      },
      color: { text: 'white', accent: NEON.purple, palette: [NEON.purple, NEON.pink, NEON.green, NEON.cyan], textGradient: GRADIENTS.headline },
      texture: { type: 'grain', intensity: 0.1 },
      decorative: ['light_beams', 'haze_particles', 'color_washes'],
      logo: { position: 'bottom-right', size: 'xs' },
      hierarchy: ['light_beams', 'headline', 'subheadline', 'body', 'cta'],
    },
  }),
  concept({
    id: 'bw_documentary', name: 'Black & White Documentary', family: 'atmospheric',
    inspiration: 'Photojournalism, Magnum Photos, documentary photography',
    references: ['Magnum Photos', 'Photojournalism', 'Henri Cartier-Bresson', 'Sebastião Salgado'],
    mood: 'Raw, honest, weight of reality',
    visualLanguage: 'Pure grayscale, high contrast, film grain, caption-style type',
    visualMetaphor: 'A black and white photograph — the absence of color makes you see more',
    focalPoints: ['Bold headline overlaid on the image zone', 'Caption-style text at bottom'],
    photographyStyle: 'Black and white documentary photography, high contrast, grain',
    designSystem: {
      background: { type: 'radial-glow', baseColor: '#0a0a0a', glow: { color: '#444444', x: 50, y: 35, intensity: 0.15 } },
      composition: { anchor: 'bottom', alignment: 'left', negativeSpace: 0.2, maxWidth: 0.85 },
      typography: {
        headline: { font: 'display', weight: 'heavy', transform: 'none', tracking: 'normal', scale: 1.2 },
        subheadline: { font: 'body', weight: 'normal', tracking: 'normal', scale: 0.85 },
      },
      color: { text: 'white', accent: '#aaaaaa', palette: ['#ffffff', '#888888', '#444444'], textGradient: null },
      texture: { type: 'grain', intensity: 0.35 },
      decorative: ['caption_bar', 'photo_credit', 'date_stamp'],
      logo: { position: 'bottom-left', size: 'xs' },
      hierarchy: ['headline', 'subheadline', 'caption_bar', 'body', 'photo_credit'],
    },
  }),

  // ═══ BRAND FAMILY ═══
  concept({
    id: 'luxury_fashion', name: 'Luxury Fashion Ad', family: 'brand',
    inspiration: 'Vogue, Dior, Hermes print advertisements',
    references: ['Vogue', 'Dior', 'Hermes', 'Chanel print ads'],
    mood: 'Aspirational, refined, covetous',
    visualLanguage: 'Full-bleed visual zone, minimal text at bottom, ultra-light type, wordmark',
    visualMetaphor: 'A full-page fashion ad — the image does 90% of the work, the text whispers',
    focalPoints: ['The image/visual zone, massive', 'Minimal text anchored at bottom'],
    photographyStyle: 'High-fashion editorial photography, studio lit, impeccable',
    designSystem: {
      background: { type: 'radial-glow', baseColor: '#08060a', glow: { color: NEON.purple, x: 50, y: 35, intensity: 0.12 } },
      composition: { anchor: 'bottom', alignment: 'center', negativeSpace: 0.4, maxWidth: 0.6 },
      typography: {
        headline: { font: 'body', weight: 'light', transform: 'uppercase', tracking: 'extra-wide', scale: 0.95 },
        subheadline: { font: 'body', weight: 'light', tracking: 'wide', scale: 0.8 },
      },
      color: { text: 'white', accent: '#cccccc', palette: ['#ffffff', '#aaaaaa'], textGradient: null },
      texture: { type: 'none', intensity: 0 },
      decorative: ['brand_wordmark'],
      logo: { position: 'bottom-center', size: 'sm' },
      hierarchy: ['headline', 'brand_wordmark', 'subheadline'],
    },
  }),
  concept({
    id: 'sports_broadcast', name: 'Sports Broadcast', family: 'brand',
    inspiration: 'ESPN, Fox Sports, NBC broadcast graphics',
    references: ['ESPN', 'Fox Sports', 'NBC Sports', 'CBS Sports graphics'],
    mood: 'Competitive, energized, stat-driven',
    visualLanguage: 'Angled graphic zones, stat boxes, bold team colors, dynamic diagonal',
    visualMetaphor: 'A broadcast lower-third — the info you need, styled like you are watching the game',
    focalPoints: ['Bold stat/headline in the graphic zone', 'Scoreboard elements flanking'],
    designSystem: {
      background: { type: 'flat', baseColor: '#0a0608', glow: { color: NEON.orange, x: 50, y: 50, intensity: 0.1 } },
      composition: { anchor: 'center', alignment: 'left', negativeSpace: 0.2, maxWidth: 0.85, rotation: 0 },
      typography: {
        headline: { font: 'display', weight: 'heavy', transform: 'uppercase', tracking: 'normal', scale: 1.2 },
        stat: { font: 'display', weight: 'heavy', transform: 'none', tracking: 'normal', scale: 1.6 },
        subheadline: { font: 'body', weight: 'bold', transform: 'uppercase', tracking: 'wide', scale: 0.9 },
      },
      color: { text: 'white', accent: NEON.orange, palette: [NEON.orange, NEON.yellow, '#ffffff'], textGradient: null },
      texture: { type: 'none', intensity: 0 },
      decorative: ['stat_boxes', 'score_ticker', 'team_stripes', 'broadcast_frame'],
      logo: { position: 'top-right', size: 'xs' },
      hierarchy: ['headline', 'stat', 'stat_boxes', 'subheadline', 'score_ticker'],
    },
  }),
  concept({
    id: 'financial_report', name: 'Financial Report', family: 'brand',
    inspiration: 'Bloomberg terminal, annual reports, WSJ graphics',
    references: ['Bloomberg terminal', 'Annual reports', 'WSJ graphics', 'Financial Times'],
    mood: 'Professional, trustworthy, data-confident',
    visualLanguage: 'Clean data grid, card-based, aligned columns, trend indicators, muted palette',
    visualMetaphor: 'A clean data dashboard — every number earns its space',
    focalPoints: ['Key stat/figure, prominent', 'Supporting data points in a clean grid'],
    designSystem: {
      background: { type: 'flat', baseColor: '#0a0a0f', glow: null },
      composition: { anchor: 'center', alignment: 'left', negativeSpace: 0.25, maxWidth: 0.85 },
      typography: {
        headline: { font: 'body', weight: 'bold', transform: 'none', tracking: 'normal', scale: 1.0 },
        stat: { font: 'display', weight: 'heavy', transform: 'none', tracking: 'normal', scale: 1.5 },
        subheadline: { font: 'body', weight: 'normal', tracking: 'normal', scale: 0.85 },
      },
      color: { text: 'white', accent: NEON.green, palette: [NEON.green, '#ffffff', '#666666'], textGradient: null },
      texture: { type: 'none', intensity: 0 },
      decorative: ['data_cards', 'trend_indicators', 'grid_lines', 'source_citation'],
      logo: { position: 'top-left', size: 'sm' },
      hierarchy: ['headline', 'stat', 'data_cards', 'subheadline', 'source_citation'],
    },
  }),
  concept({
    id: 'formula_one', name: 'Formula 1', family: 'brand',
    inspiration: 'F1 poster graphics, racing liveries, motorsport design',
    references: ['F1 graphics', 'Racing liveries', 'Motorsport design', 'Red Bull Racing'],
    mood: 'Adrenaline, precision, elite performance',
    visualLanguage: 'Carbon fiber texture, speed lines, angled type, racing red/silver, chevrons',
    visualMetaphor: 'A car at speed — motion blur, carbon fiber, the blur of the track',
    focalPoints: ['Dynamic angled headline, implying motion', 'Speed line elements racing across'],
    designSystem: {
      background: { type: 'pattern-lines', baseColor: '#08080a', glow: { color: NEON.orange, x: 70, y: 50, intensity: 0.1 }, patternColor: 'rgba(255,140,0,0.06)' },
      composition: { anchor: 'center', alignment: 'left', negativeSpace: 0.2, maxWidth: 0.85, rotation: -2 },
      typography: {
        headline: { font: 'display', weight: 'heavy', transform: 'uppercase', tracking: 'normal', scale: 1.3 },
        subheadline: { font: 'body', weight: 'bold', transform: 'uppercase', tracking: 'wide', scale: 0.85 },
      },
      color: { text: 'white', accent: NEON.orange, palette: [NEON.orange, '#cccccc', '#ffffff'], textGradient: null },
      texture: { type: 'grain', intensity: 0.1 },
      decorative: ['speed_lines', 'carbon_fiber', 'racing_number', 'chevron_accents'],
      logo: { position: 'top-right', size: 'xs' },
      hierarchy: ['speed_lines', 'headline', 'racing_number', 'subheadline', 'body', 'cta'],
    },
  }),
];

export function getConceptById(id) {
  return CREATIVE_CONCEPTS.find(c => c.id === id);
}

export function getConceptsByFamily(family) {
  return CREATIVE_CONCEPTS.filter(c => c.family === family);
}

export const CONCEPT_FAMILIES = ['poster', 'document', 'editorial', 'tech', 'atmospheric', 'brand'];

export const CONCEPT_FAMILY_LABELS = {
  poster: 'Poster',
  document: 'Document',
  editorial: 'Editorial',
  tech: 'Tech',
  atmospheric: 'Atmospheric',
  brand: 'Brand',
};